--Message = "Column 'CreatedDate' does not allow DBNull.Value."
--                   CreatedDate

drop table if exists AccountTransaction

create table AccountTransaction
(
	AccountTransactionId int identity (1,1),
	Account varchar(128),
	Description varchar(256),
	CurrencyCode char(3),
	Amount DECIMAL(19,4),
	--CreatedDate datetime null constraint df_AccountTransaction_CreatedDate default (GETDATE()),
	FileUploadId int null,
	constraint pk_TransactionUpload primary key (AccountTransactionId)
)

drop table if exists FileUpload

create table FileUpload
(
	FileUploadId int identity (1,1),
	FileName varchar(255),
	UploadDate datetime2,
	NumberOfRecords int,
	NumberOfSuccessfullRecords int,
	constraint pk_FileUpload primary key (FileUploadId)
)


drop table if exists CurrencyCode

create table CurrencyCode
(
	CurrencyCode char(3),
	Currency varchar(256),
	constraint pk_CurrencyCode primary key (CurrencyCode)
)

insert CurrencyCode values ('ALL','Albanian lek')
insert CurrencyCode values ('AMD','Armenian dram')
insert CurrencyCode values ('ANG','Netherlands Antillean guilder')
insert CurrencyCode values ('AOA','Angolan kwanza')
insert CurrencyCode values ('ARS','Argentine peso')
insert CurrencyCode values ('AUD','Australian dollar')
insert CurrencyCode values ('AWG','Aruban florin')
insert CurrencyCode values ('AZN','Azerbaijani manat')
insert CurrencyCode values ('BAM','Bosnia and Herzegovina convertible mark')
insert CurrencyCode values ('BBD','Barbados dollar')
insert CurrencyCode values ('BDT','Bangladeshi taka')
insert CurrencyCode values ('BGN','Bulgarian lev')
insert CurrencyCode values ('BHD','Bahraini dinar')
insert CurrencyCode values ('BIF','Burundian franc')
insert CurrencyCode values ('BMD','Bermudian dollar')
insert CurrencyCode values ('BND','Brunei dollar')
insert CurrencyCode values ('BOB','Boliviano')
insert CurrencyCode values ('BOV','Bolivian Mvdol (funds code)')
insert CurrencyCode values ('BRL','Brazilian real')
insert CurrencyCode values ('BSD','Bahamian dollar')
insert CurrencyCode values ('BTN','Bhutanese ngultrum')
insert CurrencyCode values ('BWP','Botswana pula')
insert CurrencyCode values ('BYN','Belarusian ruble')
insert CurrencyCode values ('BZD','Belize dollar')
insert CurrencyCode values ('CAD','Canadian dollar')
insert CurrencyCode values ('CDF','Congolese franc')
insert CurrencyCode values ('CHE','WIR Euro (complementary currency)')
insert CurrencyCode values ('CHF','Swiss franc')
insert CurrencyCode values ('CHW','WIR Franc (complementary currency)')
insert CurrencyCode values ('CLF','Unidad de Fomento (funds code)')
insert CurrencyCode values ('CLP','Chilean peso')
insert CurrencyCode values ('CNY','Renminbi (Chinese) yuan[8]')
insert CurrencyCode values ('COP','Colombian peso')
insert CurrencyCode values ('COU','Unidad de Valor Real (UVR) (funds code)[9]')
insert CurrencyCode values ('CRC','Costa Rican colon')
insert CurrencyCode values ('CUC','Cuban convertible peso')
insert CurrencyCode values ('CUP','Cuban peso')
insert CurrencyCode values ('CVE','Cape Verde escudo')
insert CurrencyCode values ('CZK','Czech koruna')
insert CurrencyCode values ('DJF','Djiboutian franc')
insert CurrencyCode values ('DKK','Danish krone')
insert CurrencyCode values ('DOP','Dominican peso')
insert CurrencyCode values ('DZD','Algerian dinar')
insert CurrencyCode values ('EGP','Egyptian pound')
insert CurrencyCode values ('ERN','Eritrean nakfa')
insert CurrencyCode values ('ETB','Ethiopian birr')
insert CurrencyCode values ('EUR','Euro')
insert CurrencyCode values ('FJD','Fiji dollar')
insert CurrencyCode values ('FKP','Falkland Islands pound')
insert CurrencyCode values ('GBP','Pound sterling')
insert CurrencyCode values ('GEL','Georgian lari')
insert CurrencyCode values ('GHS','Ghanaian cedi')
insert CurrencyCode values ('GIP','Gibraltar pound')
insert CurrencyCode values ('GMD','Gambian dalasi')
insert CurrencyCode values ('GNF','Guinean franc')
insert CurrencyCode values ('GTQ','Guatemalan quetzal')
insert CurrencyCode values ('GYD','Guyanese dollar')
insert CurrencyCode values ('HKD','Hong Kong dollar')
insert CurrencyCode values ('HNL','Honduran lempira')
insert CurrencyCode values ('HRK','Croatian kuna')
insert CurrencyCode values ('HTG','Haitian gourde')
insert CurrencyCode values ('HUF','Hungarian forint')
insert CurrencyCode values ('IDR','Indonesian rupiah')
insert CurrencyCode values ('ILS','Israeli new shekel')
insert CurrencyCode values ('INR','Indian rupee')
insert CurrencyCode values ('IQD','Iraqi dinar')
insert CurrencyCode values ('IRR','Iranian rial')
insert CurrencyCode values ('ISK','Icelandic króna')
insert CurrencyCode values ('JMD','Jamaican dollar')
insert CurrencyCode values ('JOD','Jordanian dinar')
insert CurrencyCode values ('JPY','Japanese yen')
insert CurrencyCode values ('KES','Kenyan shilling')
insert CurrencyCode values ('KGS','Kyrgyzstani som')
insert CurrencyCode values ('KHR','Cambodian riel')
insert CurrencyCode values ('KMF','Comoro franc')
insert CurrencyCode values ('KPW','North Korean won')
insert CurrencyCode values ('KRW','South Korean won')
insert CurrencyCode values ('KWD','Kuwaiti dinar')
insert CurrencyCode values ('KYD','Cayman Islands dollar')
insert CurrencyCode values ('KZT','Kazakhstani tenge')
insert CurrencyCode values ('LAK','Lao kip')
insert CurrencyCode values ('LBP','Lebanese pound')
insert CurrencyCode values ('LKR','Sri Lankan rupee')
insert CurrencyCode values ('LRD','Liberian dollar')
insert CurrencyCode values ('LSL','Lesotho loti')
insert CurrencyCode values ('LYD','Libyan dinar')
insert CurrencyCode values ('MAD','Moroccan dirham')
insert CurrencyCode values ('MDL','Moldovan leu')
insert CurrencyCode values ('MGA','Malagasy ariary')
insert CurrencyCode values ('MKD','Macedonian denar')
insert CurrencyCode values ('MMK','Myanmar kyat')
insert CurrencyCode values ('MNT','Mongolian tögrög')
insert CurrencyCode values ('MOP','Macanese pataca')
insert CurrencyCode values ('MRU','Mauritanian ouguiya')
insert CurrencyCode values ('MUR','Mauritian rupee')
insert CurrencyCode values ('MVR','Maldivian rufiyaa')
insert CurrencyCode values ('MWK','Malawian kwacha')
insert CurrencyCode values ('MXN','Mexican peso')
insert CurrencyCode values ('MXV','Mexican Unidad de Inversion (UDI) (funds code)')
insert CurrencyCode values ('MYR','Malaysian ringgit')
insert CurrencyCode values ('MZN','Mozambican metical')
insert CurrencyCode values ('NAD','Namibian dollar')
insert CurrencyCode values ('NGN','Nigerian naira')
insert CurrencyCode values ('NIO','Nicaraguan córdoba')
insert CurrencyCode values ('NOK','Norwegian krone')
insert CurrencyCode values ('NPR','Nepalese rupee')
insert CurrencyCode values ('NZD','New Zealand dollar')
insert CurrencyCode values ('OMR','Omani rial')
insert CurrencyCode values ('PAB','Panamanian balboa')
insert CurrencyCode values ('PEN','Peruvian Sol')
insert CurrencyCode values ('PGK','Papua New Guinean kina')
insert CurrencyCode values ('PHP','Philippine piso[13]')
insert CurrencyCode values ('PKR','Pakistani rupee')
insert CurrencyCode values ('PLN','Polish złoty')
insert CurrencyCode values ('PYG','Paraguayan guaraní')
insert CurrencyCode values ('QAR','Qatari riyal')
insert CurrencyCode values ('RON','Romanian leu')
insert CurrencyCode values ('RSD','Serbian dinar')
insert CurrencyCode values ('RUB','Russian ruble')
insert CurrencyCode values ('RWF','Rwandan franc')
insert CurrencyCode values ('SAR','Saudi riyal')
insert CurrencyCode values ('SBD','Solomon Islands dollar')
insert CurrencyCode values ('SCR','Seychelles rupee')
insert CurrencyCode values ('SDG','Sudanese pound')
insert CurrencyCode values ('SEK','Swedish krona/kronor')
insert CurrencyCode values ('SGD','Singapore dollar')
insert CurrencyCode values ('SHP','Saint Helena pound')
insert CurrencyCode values ('SLL','Sierra Leonean leone')
insert CurrencyCode values ('SOS','Somali shilling')
insert CurrencyCode values ('SRD','Surinamese dollar')
insert CurrencyCode values ('SSP','South Sudanese pound')
insert CurrencyCode values ('STN','São Tomé and Príncipe dobra')
insert CurrencyCode values ('SVC','Salvadoran colón')
insert CurrencyCode values ('SYP','Syrian pound')
insert CurrencyCode values ('SZL','Swazi lilangeni')
insert CurrencyCode values ('THB','Thai baht')
insert CurrencyCode values ('TJS','Tajikistani somoni')
insert CurrencyCode values ('TMT','Turkmenistan manat')
insert CurrencyCode values ('TND','Tunisian dinar')
insert CurrencyCode values ('TOP','Tongan paʻanga')
insert CurrencyCode values ('TRY','Turkish lira')
insert CurrencyCode values ('TTD','Trinidad and Tobago dollar')
insert CurrencyCode values ('TWD','New Taiwan dollar')
insert CurrencyCode values ('TZS','Tanzanian shilling')
insert CurrencyCode values ('UAH','Ukrainian hryvnia')
insert CurrencyCode values ('UGX','Ugandan shilling')
insert CurrencyCode values ('USD','United States dollar')
insert CurrencyCode values ('USN','United States dollar (next day) (funds code)')
insert CurrencyCode values ('UYI','Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)')
insert CurrencyCode values ('UYU','Uruguayan peso')
insert CurrencyCode values ('UZS','Uzbekistan som')
insert CurrencyCode values ('VEF','Venezuelan bolívar')
insert CurrencyCode values ('VND','Vietnamese đồng')
insert CurrencyCode values ('VUV','Vanuatu vatu')
insert CurrencyCode values ('WST','Samoan tala')
insert CurrencyCode values ('XAF','CFA franc BEAC')
insert CurrencyCode values ('XAG','Silver (one troy ounce)')
insert CurrencyCode values ('XAU','Gold (one troy ounce)')
insert CurrencyCode values ('XBA','European Composite Unit(EURCO) (bond market unit)')
insert CurrencyCode values ('XBB','European Monetary Unit(E.M.U.-6) (bond market unit)')
insert CurrencyCode values ('XBC','European Unit of Account 9(E.U.A.-9) (bond market unit)')
insert CurrencyCode values ('XBD','European Unit of Account 17(E.U.A.-17) (bond market unit)')
insert CurrencyCode values ('XCD','East Caribbean dollar')
insert CurrencyCode values ('XDR','Special drawing rights')
insert CurrencyCode values ('XOF','CFA franc BCEAO')
insert CurrencyCode values ('XPD','Palladium (one troy ounce)')
insert CurrencyCode values ('XPF','CFP franc (franc Pacifique)')
insert CurrencyCode values ('XPT','Platinum (one troy ounce)')
insert CurrencyCode values ('XSU','SUCRE')
insert CurrencyCode values ('XTS','Code reserved for testing purposes')
insert CurrencyCode values ('XUA','ADB Unit of Account')
insert CurrencyCode values ('XXX','No currency')
insert CurrencyCode values ('YER','Yemeni rial')
insert CurrencyCode values ('ZAR','South African rand')
insert CurrencyCode values ('ZMW','Zambian kwacha')
insert CurrencyCode values ('ZWL','Zimbabwean dollar A/10')


ALTER TABLE AccountTransaction
ADD FOREIGN KEY (FileUploadId) REFERENCES FileUpload(FileUploadId);

ALTER TABLE AccountTransaction
ADD FOREIGN KEY (CurrencyCode) REFERENCES CurrencyCode(CurrencyCode);

----


